# Generated by Django 4.2.6 on 2023-10-31 07:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appweb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AddField(
            model_name="lesson",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="lessons", to="appweb.tag"
            ),
        ),
    ]
